### ISSUE TITLE
there is no json file inside libs/datasets/

### ISSUE THREAD

**Issue by pongopal** [c-feng/DirectionalFeature#1]
The program won't work until  libs/dataset/gen_acdcjson has json files. Can you share the json files>

**Comment by cheng321284** [comment]
You can refer to the `def gen_alldatalist(path):` function in `gen_acdcjson.py`  to make your json file, which contains your data path~

**Comment by cheng321284** [comment]
> The program won't work until libs/dataset/gen_acdcjson has json files. Can you share the json files>

You can refer to the def gen_alldatalist(path): function in gen_acdcjson.py to make your json file, which contains your data path~

**Comment by cheng321284** [comment]
> The program won't work until libs/dataset/gen_acdcjson has json files. Can you share the json files>

You can refer to the def `gen_alldatalist(path): ` function in `gen_acdcjson.py` to make your json file, which contains your data path~
