### ISSUE TITLE
testing script?

### ISSUE THREAD

**Issue by pongopal** [c-feng/DirectionalFeature#2]
Which test script have you run for the evaluation and visualization?

**Comment by cheng321284** [comment]
`test_df_vis.py` for self-test and `test_acdc_leadboard.py` to generate data in the data format corresponding to the challenge.

**Comment by cheng321284** [comment]
> Which test script have you run for the evaluation and visualization?

`test_df_vis.py` for self-test and `test_acdc_leadboard.py` to generate data in the data format corresponding to the challenge. @pongopal
